# Shell completion generators for corral.
# shellcheck shell=bash
# shellcheck disable=SC2154
# Each _completions_<shell>() function emits a heredoc of shell-native
# completion code; the output is written to the appropriate completions
# directory by install_completions() in corral-runtime.sh.

# Generate Fish shell completions for corral.
# Fish uses the __fish_seen_subcommand_from helper to scope completions
# to specific subcommands, with -n conditions as guards.
_completions_fish() {
  local sn="$SCRIPT_NAME"
  cat <<EOF
# Fish completions for $sn  (generated by: $sn install)

set -l commands install update versions prune uninstall status search browse pull list ls remove rm run serve ps profile template help

# Disable file completion for all subcommands.
complete -c $sn -f

# Top-level commands.
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a install   -d 'Install inference backend'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a update    -d 'Update backend components'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a versions  -d 'Show installed backend versions'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a prune     -d 'Prune backend-managed state'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a uninstall -d 'Uninstall backend components'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a status    -d 'Show backend and version status'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a search    -d 'Search backend-compatible models'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a browse    -d 'Open a model HuggingFace page in browser'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a pull      -d 'Prefetch model artifacts'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a list      -d 'List backend-scoped cached models'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a ls        -d 'List backend-scoped cached models (alias)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a remove    -d 'Remove backend-scoped model cache entry'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a rm        -d 'Remove backend-scoped model cache entry (alias)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a run       -d 'Run a model (mlx or llama.cpp)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a serve     -d 'Serve a model (mlx or llama.cpp)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a ps        -d 'Show running llama processes'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a profile   -d 'Manage named run/serve profiles'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a template  -d 'Manage templates'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a help      -d 'Show help'

# Flags per subcommand.
complete -c $sn -n "__fish_seen_subcommand_from install"     -l tag              -d 'Release tag'
complete -c $sn -n "__fish_seen_subcommand_from install update versions prune uninstall status search pull list ls remove rm run serve" -l backend -a "mlx llama.cpp" -d 'Backend'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l arch           -d 'Architecture (e.g. macos-arm64)'
complete -c $sn -n "__fish_seen_subcommand_from install update versions prune uninstall status" -l path -d 'Installation root'
complete -c $sn -n "__fish_seen_subcommand_from install"     -l print-latest-tag -d 'Print latest tag and exit'
complete -c $sn -n "__fish_seen_subcommand_from status"      -l check-update     -d 'Check for newer release'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l shell-profile   -d 'Allow shell profile edits'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l no-shell-profile -d 'Skip shell profile edits'
complete -c $sn -n "__fish_seen_subcommand_from uninstall"   -l delete-hf-cache  -d 'Delete cached HF model dirs'
complete -c $sn -n "__fish_seen_subcommand_from uninstall"   -l self             -d 'Also delete the corral script itself'
complete -c $sn -n "__fish_seen_subcommand_from uninstall remove rm prune" -l force    -d 'Skip confirmation prompt'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l quiet            -d 'Only print names'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l json             -d 'JSON output'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l models           -d 'Show models only'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l profiles         -d 'Show profiles only'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l templates        -d 'Show templates only'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l sort             -d 'Sort order (trending, downloads, likes, newest)'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l limit            -d 'Maximum number of results'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l quants           -d 'Show available quant variants'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l quiet            -d 'Only print model identifiers'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l json             -d 'JSON output'
complete -c $sn -n "__fish_seen_subcommand_from browse"      -l print            -d 'Print URL instead of opening browser'
complete -c $sn -n "__fish_seen_subcommand_from browse pull" -a "(__corral_cached_models)"
complete -c $sn -n "__fish_seen_subcommand_from run serve" -a "(__corral_cached_models) (__corral_profiles)"
complete -c $sn -n "__fish_seen_subcommand_from remove rm"   -a "(__corral_removal_targets)"

# Profile subcommand completions.
set -l profile_subcmds set show duplicate
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a set       -d 'Create or replace a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a show      -d 'Print a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a duplicate -d 'Copy a profile to a new name'
complete -c $sn -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show duplicate" -a "(__corral_profiles)"
complete -c $sn -n "__corral_profile_set_needs_target" -a "(__corral_templates) (__corral_cached_models)"
complete -c $sn -n "__corral_profile_set_needs_model" -a "(__corral_cached_models)"

# Template subcommand completions.
set -l template_subcmds show set remove rm
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a show   -d 'Print a template'
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a set    -d 'Create or replace a user-defined template'
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a remove -d 'Delete a user-defined template'
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a rm     -d 'Delete a user-defined template (alias)'
complete -c $sn -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from show remove rm" -a "(__corral_templates)"

# Model name completion for commands that take MODEL_NAME[:QUANT].
function __corral_cached_models
  corral ls --quiet --models 2>/dev/null | awk 'index(\$0, "/") > 0 { print \$0 }'
end

function __corral_cached_models_no_quant
  corral ls --quiet --models 2>/dev/null | awk 'index(\$0, "/") > 0 { sub(/:.*/, "", \$0); print \$0 }' | awk '!seen[\$0]++'
end

function __corral_runtime_backend
  set -l argv (commandline -opc)
  set -l expect_backend 0
  for tok in \$argv
    if test "\$expect_backend" = "1"
      echo "\$tok"
      return 0
    end
    if test "\$tok" = "--backend"
      set expect_backend 1
    end
  end

  if test (uname -s) = Darwin; and test (uname -m) = arm64
    echo mlx
  else
    echo llama.cpp
  end
end

function __corral_profiles
  corral ls --quiet --profiles 2>/dev/null | awk 'NF == 1 && index(\$0, " ") == 0 { print \$0 }'
end

function __corral_templates
  corral ls --quiet --templates 2>/dev/null | awk 'NF == 1 && index(\$0, " ") == 0 { print \$0 }'
end

function __corral_profile_set_positionals
  set -l words (commandline -opc)
  if test (count \$words) -lt 4
    return 1
  end

  if test "\$words[2]" != "profile"; or test "\$words[3]" != "set"
    return 1
  end

  for tok in \$words[4..-1]
    if test "\$tok" = "--"
      break
    end
    echo "\$tok"
  end
end

function __corral_profile_set_needs_target
  set -l args (__corral_profile_set_positionals)
  test (count \$args) -eq 1
end

function __corral_profile_set_needs_model
  set -l args (__corral_profile_set_positionals)
  if test (count \$args) -ne 2
    return 1
  end

  contains -- "\$args[2]" (__corral_templates)
end

function __corral_removal_targets
  __corral_cached_models
  __corral_profiles
end
EOF
}

# Generate Zsh completions for corral.
# Uses Zsh's _arguments state-machine approach with a nested case for profile
# subcommands. The heredoc uses a quoted delimiter ('ZSHEOF') so that bash
# does not expand the $, (), and other Zsh-specific syntax inside the body.
_completions_zsh() {
  local sn="$SCRIPT_NAME"
  cat <<'ZSHEOF'
#compdef corral
# Zsh completions for corral  (generated by: corral install)

_corral_cached_models() {
  local specs
  specs=(${(f)"$(corral ls --quiet --models 2>/dev/null | awk 'index($0, "/") > 0 { print $0 }')"})
  (( ${#specs[@]} )) && _values 'model[:quant]' "${specs[@]}"
}

_corral_cached_models_no_quant() {
  local specs
  specs=(${(f)"$(corral ls --quiet --models 2>/dev/null | awk 'index($0, "/") > 0 { sub(/:.*/, "", $0); print $0 }' | awk '!seen[$0]++')"})
  (( ${#specs[@]} )) && _values 'model' "${specs[@]}"
}

_corral_profiles() {
  local names
  names=(${(f)"$(corral ls --quiet --profiles 2>/dev/null | awk 'NF == 1 && index($0, " ") == 0 { print $0 }')"})
  (( ${#names[@]} )) && _values 'profile' "${names[@]}"
}

_corral_templates() {
  local names
  names=(${(f)"$(corral ls --quiet --templates 2>/dev/null | awk 'NF == 1 && index($0, " ") == 0 { print $0 }')"})
  (( ${#names[@]} )) && _values 'template' "${names[@]}"
}

_corral_has_template() {
  local target="$1"
  local names
  names=(${(f)"$(corral ls --quiet --templates 2>/dev/null | awk 'NF == 1 && index($0, " ") == 0 { print $0 }')"})
  (( ${names[(Ie)$target]} ))
}

_corral_removal_targets() {
  _alternative 'models:model:_corral_cached_models' 'profiles:profile:_corral_profiles'
}

_corral() {
  local state
  _arguments \
    '1:command:->cmd' \
    '*::options:->opts'
  case $state in
    cmd)
      local cmds=(
        'install:Install inference backend'
        'update:Update backend components'
        'versions:Show installed backend versions'
        'prune:Prune backend-managed state'
        'uninstall:Uninstall backend components'
        'status:Show backend and version status'
        'search:Search backend-compatible models'
        'browse:Open a model HuggingFace page in browser'
        'pull:Prefetch model artifacts'
        'list:List backend-scoped cached models' 'ls:List backend-scoped cached models'
        'remove:Remove backend-scoped model cache entry' 'rm:Remove backend-scoped model cache entry'
        'run:Run a model (mlx or llama.cpp)'
        'serve:Serve a model (mlx or llama.cpp)'
        'ps:Show running llama processes'
        'profile:Manage named run/serve profiles'
        'template:Manage templates'
        'help:Show help'
      )
      _describe 'command' cmds ;;
    opts)
      case $words[1] in
        install)
          _arguments \
            '--backend[Backend]:backend:(mlx llama.cpp)' \
            '--tag[Release tag]:tag' \
            '--path[Installation root]:dir:_files -/' \
            '--arch[Architecture]:arch:(macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64)' \
            '--shell-profile[Allow shell profile edits]' \
            '--no-shell-profile[Skip shell profile edits]' \
            '--print-latest-tag[Print latest tag and exit]' ;;
        update)
          _arguments \
            '--backend[Backend]:backend:(mlx llama.cpp)' \
            '--path[Installation root]:dir:_files -/' \
            '--arch[Architecture]:arch:(macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64)' \
            '--shell-profile[Allow shell profile edits]' \
            '--no-shell-profile[Skip shell profile edits]' ;;
        uninstall)
          _arguments \
            '--backend[Backend]:backend:(mlx llama.cpp)' \
            '--path[Installation root]:dir:_files -/' \
            '--delete-hf-cache[Delete cached HF model dirs]' \
            '--self[Also delete the corral script itself]' \
            '--force[Skip confirmation prompt]' ;;
        status)
          _arguments \
            '--backend[Backend]:backend:(mlx llama.cpp)' \
            '--path[Installation root]:dir:_files -/' \
            '--check-update[Check for newer release]' ;;
        search)
          _arguments \
            '--backend[Backend]:backend:(mlx llama.cpp)' \
            '--sort[Sort order]:by:(trending downloads likes newest)' \
            '--limit[Maximum number of results]:n' \
            '--quants[Show available quant variants]' \
            '--quiet[Only print model identifiers]' \
            '--json[JSON output]' ;;
        browse)
          _arguments '--print[Print URL instead of opening browser]' && _corral_cached_models ;;
        list|ls)
          _arguments '--backend[Backend]:backend:(mlx llama.cpp)' '--quiet[Only print names]' '--json[JSON output]' '--models[Show models only]' '--profiles[Show profiles only]' '--templates[Show templates only]' ;;
        remove|rm)
          _arguments '--backend[Backend]:backend:(mlx llama.cpp)' '--force[Skip confirmation prompt]' && _corral_removal_targets ;;
        pull)
          _arguments '--backend[Backend]:backend:(mlx llama.cpp)' && _corral_cached_models ;;
        run|serve)
          _arguments '--backend[Backend]:backend:(mlx llama.cpp)'
          { _corral_cached_models; _corral_profiles } ;;
        profile)
          _arguments '1:subcommand:->sub' '*::profile-opts:->popts'
          case $state in
            sub)
              local subcmds=(
                'set:Create or replace a profile'
                'show:Print a profile'
                'duplicate:Copy a profile to a new name'
              )
              _describe 'profile subcommand' subcmds ;;
            popts)
              case $words[2] in
                set)
                  if (( CURRENT == 4 )); then
                    _alternative 'templates:template:_corral_templates' 'models:model:_corral_cached_models'
                  elif (( CURRENT == 5 )); then
                    if _corral_has_template "$words[4]"; then
                      _corral_cached_models
                    fi
                  fi ;;
                show|duplicate) _corral_profiles ;;
              esac ;;
          esac ;;
        template)
          _arguments '1:subcommand:->sub' '*::template-opts:->topts'
          case $state in
            sub)
              local tsubcmds=(
                'show:Print a template'
                'set:Create or replace a user-defined template'
                'remove:Delete a user-defined template'
                'rm:Delete a user-defined template'
              )
              _describe 'template subcommand' tsubcmds ;;
            topts)
              case $words[2] in
                show|remove|rm) _corral_templates ;;
              esac ;;
          esac ;;
        versions)
          _arguments '--backend[Backend]:backend:(mlx llama.cpp)' '--path[Installation root]:dir:_files -/' ;;
        prune)
          _arguments \
            '--backend[Backend]:backend:(mlx llama.cpp)' \
            '--path[Installation root]:dir:_files -/' \
            '--force[Skip confirmation prompt]' ;;
      esac ;;
  esac
}

_corral
ZSHEOF
}

# Generate Bash completions for corral.
# Registers a _corral_completions() function via 'complete -F'.
#
# COMP_WORDBREAKS: bash completion normally splits on ':', which would break
# "user/model:Q4_K_M" into two separate tokens. COMP_WORDBREAKS is narrowed
# (removing ':') for the duration of the completion call so that
# model:quant strings are treated as a single token for matching.
_completions_bash() {
  local sn="$SCRIPT_NAME"
  cat <<EOF
# Bash completions for $sn  (generated by: $sn install)
_${sn//-/_}_completions() {
  local cur prev words cword
  local _saved_wb="\$COMP_WORDBREAKS"
  COMP_WORDBREAKS="\${COMP_WORDBREAKS//:}"
  _init_completion 2>/dev/null || { cur="\${COMP_WORDS[COMP_CWORD]}"; prev="\${COMP_WORDS[COMP_CWORD-1]}"; }
  # shellcheck disable=SC2154
  local commands="install update versions prune uninstall status search browse pull list ls remove rm run serve ps profile template help"
  if [[ \$COMP_CWORD -eq 1 ]]; then
    COMPREPLY=(\$(compgen -W "\$commands" -- "\$cur"))
    COMP_WORDBREAKS="\$_saved_wb"
    return
  fi
  local cmd="\${COMP_WORDS[1]}"
  local -a models=() models_no_quant=() profiles=() templates=()
  while IFS= read -r _yl; do
    [[ -n "\$_yl" ]] && models+=("\$_yl")
  done < <(corral ls --quiet --models 2>/dev/null | awk 'index(\$0, "/") > 0 { print \$0 }')
  while IFS= read -r _ym; do
    [[ -n "\$_ym" ]] && models_no_quant+=("\$_ym")
  done < <(corral ls --quiet --models 2>/dev/null | awk 'index(\$0, "/") > 0 { sub(/:.*/, "", \$0); print \$0 }' | awk '!seen[\$0]++')
  while IFS= read -r _yp; do
    [[ -n "\$_yp" ]] && profiles+=("\$_yp")
  done < <(corral ls --quiet --profiles 2>/dev/null | awk 'NF == 1 && index(\$0, " ") == 0 { print \$0 }')
  while IFS= read -r _yt; do
    [[ -n "\$_yt" ]] && templates+=("\$_yt")
  done < <(corral ls --quiet --templates 2>/dev/null | awk 'NF == 1 && index(\$0, " ") == 0 { print \$0 }')

  local models_words="" models_no_quant_words="" profiles_words="" templates_words="" removables_words=""
  (( \${#models[@]} > 0 )) && models_words="\${models[*]}"
  (( \${#models_no_quant[@]} > 0 )) && models_no_quant_words="\${models_no_quant[*]}"
  (( \${#profiles[@]} > 0 )) && profiles_words="\${profiles[*]}"
  (( \${#templates[@]} > 0 )) && templates_words="\${templates[*]}"
  if [[ -n "\$models_words" && -n "\$profiles_words" ]]; then
    removables_words="\$models_words \$profiles_words"
  elif [[ -n "\$models_words" ]]; then
    removables_words="\$models_words"
  else
    removables_words="\$profiles_words"
  fi

  case "\$prev" in
    --path)  COMPREPLY=(\$(compgen -d -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --shell) COMPREPLY=(\$(compgen -W "fish zsh bash" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --arch)  COMPREPLY=(\$(compgen -W "macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --backend) COMPREPLY=(\$(compgen -W "mlx llama.cpp" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --sort)  COMPREPLY=(\$(compgen -W "trending downloads likes newest" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
  esac
  case "\$cmd" in
    install)  COMPREPLY=(\$(compgen -W "--backend --tag --path --arch --shell-profile --no-shell-profile --print-latest-tag" -- "\$cur")) ;;
    update)   COMPREPLY=(\$(compgen -W "--backend --path --arch --shell-profile --no-shell-profile" -- "\$cur")) ;;
    uninstall) COMPREPLY=(\$(compgen -W "--backend --path --delete-hf-cache --self --force" -- "\$cur")) ;;
    status)   COMPREPLY=(\$(compgen -W "--backend --path --check-update" -- "\$cur")) ;;
    search)   COMPREPLY=(\$(compgen -W "--backend --sort --limit --quants --quiet --json" -- "\$cur")) ;;
    browse)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--print" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\$models_words" -- "\$cur"))
      fi ;;
    list|ls)  COMPREPLY=(\$(compgen -W "--backend --quiet --json --models --profiles --templates" -- "\$cur")) ;;
    pull)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--backend" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\$models_words" -- "\$cur"))
      fi ;;
    run|serve)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--backend" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\$models_words \$profiles_words" -- "\$cur"))
      fi ;;
    remove|rm)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--backend --force" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\$removables_words" -- "\$cur"))
      fi ;;
    profile)
      local profile_subcmds="set show duplicate"
      if [[ \$COMP_CWORD -eq 2 ]]; then
        COMPREPLY=(\$(compgen -W "\$profile_subcmds" -- "\$cur"))
      else
        local sub="\${COMP_WORDS[2]}"
        case "\$sub" in
          set)
            if [[ "\$cur" == --* ]]; then
              COMPREPLY=(\$(compgen -W "--" -- "\$cur"))
            elif [[ \$COMP_CWORD -eq 4 ]]; then
              COMPREPLY=(\$(compgen -W "\$templates_words \$models_words" -- "\$cur"))
            elif [[ \$COMP_CWORD -eq 5 ]]; then
              local target_word="\${COMP_WORDS[4]}"
              local target_is_template=0
              local _template
              for _template in "\${templates[@]}"; do
                if [[ "\$_template" == "\$target_word" ]]; then
                  target_is_template=1
                  break
                fi
              done
              if [[ \$target_is_template -eq 1 ]]; then
                COMPREPLY=(\$(compgen -W "\$models_words" -- "\$cur"))
              fi
            fi ;;
          show|duplicate) COMPREPLY=(\$(compgen -W "\$profiles_words" -- "\$cur")) ;;
        esac
      fi ;;
    template)
      local template_subcmds="show set remove rm"
      if [[ \$COMP_CWORD -eq 2 ]]; then
        COMPREPLY=(\$(compgen -W "\$template_subcmds" -- "\$cur"))
      else
        local tsub="\${COMP_WORDS[2]}"
        case "\$tsub" in
          set)
            if [[ "\$cur" == --* ]]; then
              COMPREPLY=(\$(compgen -W "--backend --" -- "\$cur"))
            fi ;;
          show|remove|rm) COMPREPLY=(\$(compgen -W "\$templates_words" -- "\$cur")) ;;
        esac
      fi ;;
    versions) COMPREPLY=(\$(compgen -W "--backend --path" -- "\$cur")) ;;
    prune)    COMPREPLY=(\$(compgen -W "--backend --path --force" -- "\$cur")) ;;
  esac
  COMP_WORDBREAKS="\$_saved_wb"
}
complete -F _${sn//-/_}_completions $sn
EOF
}
