# Shell completion generators for fold.
# shellcheck shell=bash
# shellcheck disable=SC2154
# Each _completions_<shell>() function emits a heredoc of shell-native
# completion code; the output is written to the appropriate completions
# directory by install_completions() in fold-runtime.sh.

# Generate Fish shell completions for fold.
# Fish uses the __fish_seen_subcommand_from helper to scope completions
# to specific subcommands, with -n conditions as guards.
_completions_fish() {
  local sn="$SCRIPT_NAME"
  cat <<EOF
# Fish completions for $sn  (generated by: $sn install)

set -l commands install update versions prune uninstall status search browse pull list ls remove rm run serve ps profile template help

# Disable file completion for all subcommands.
complete -c $sn -f

# Top-level commands.
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a install   -d 'Install llama.cpp'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a update    -d 'Update llama.cpp to latest'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a versions  -d 'List installed llama.cpp versions'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a prune     -d 'Remove old llama.cpp versions'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a uninstall -d 'Uninstall llama.cpp'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a status    -d 'Show installed version'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a search    -d 'Search HuggingFace for compatible GGUF models'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a browse    -d 'Open a model HuggingFace page in browser'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a pull      -d 'Download a model without running'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a list      -d 'List cached models'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a ls        -d 'List cached models (alias)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a remove    -d 'Remove a cached model'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a rm        -d 'Remove a cached model (alias)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a run       -d 'Run a model'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a serve     -d 'Serve a model'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a ps        -d 'Show running llama processes'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a profile   -d 'Manage named run/serve profiles'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a template  -d 'Manage templates'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a help      -d 'Show help'

# Flags per subcommand.
complete -c $sn -n "__fish_seen_subcommand_from install"     -l tag              -d 'Release tag'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l arch           -d 'Architecture (e.g. macos-arm64)'
complete -c $sn -n "__fish_seen_subcommand_from install update versions prune uninstall status" -l path -d 'Installation root'
complete -c $sn -n "__fish_seen_subcommand_from install"     -l print-latest-tag -d 'Print latest tag and exit'
complete -c $sn -n "__fish_seen_subcommand_from status"      -l check-update     -d 'Check for newer release'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l shell-profile   -d 'Allow shell profile edits'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l no-shell-profile -d 'Skip shell profile edits'
complete -c $sn -n "__fish_seen_subcommand_from uninstall"   -l delete-hf-cache  -d 'Delete cached HF model dirs'
complete -c $sn -n "__fish_seen_subcommand_from uninstall"   -l self             -d 'Also delete the fold script itself'
complete -c $sn -n "__fish_seen_subcommand_from uninstall remove rm prune" -l force    -d 'Skip confirmation prompt'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l quiet            -d 'Only print names'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l json             -d 'JSON output'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l models           -d 'Show models only'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l profiles         -d 'Show profiles only'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l templates        -d 'Show templates only'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l sort             -d 'Sort order (trending, downloads, likes, newest)'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l limit            -d 'Maximum number of results'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l quants           -d 'Show available quant variants'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l quiet            -d 'Only print model identifiers'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l json             -d 'JSON output'
complete -c $sn -n "__fish_seen_subcommand_from browse"      -l print            -d 'Print URL instead of opening browser'
complete -c $sn -n "__fish_seen_subcommand_from browse pull" -a "(__fold_cached_models)"
complete -c $sn -n "__fish_seen_subcommand_from run serve"   -a "(__fold_cached_models) (__fold_profiles)"
complete -c $sn -n "__fish_seen_subcommand_from remove rm"   -a "(__fold_removal_targets)"

# Profile subcommand completions.
set -l profile_subcmds set show duplicate
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a set       -d 'Create or replace a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a show      -d 'Print a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a duplicate -d 'Copy a profile to a new name'
complete -c $sn -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show duplicate" -a "(__fold_profiles)"

# Template subcommand completions.
set -l template_subcmds show set remove rm
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a show   -d 'Print a template'
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a set    -d 'Create or replace a user-defined template'
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a remove -d 'Delete a user-defined template'
complete -c $sn -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from \$template_subcmds" -a rm     -d 'Delete a user-defined template (alias)'
complete -c $sn -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from show remove rm" -a "(__fold_templates)"

# Model name completion for commands that take MODEL_NAME[:QUANT].
function __fold_cached_models
  fold ls --quiet --models 2>/dev/null | awk 'index(\$0, "/") > 0 { print \$0 }'
end

function __fold_profiles
  fold ls --quiet --profiles 2>/dev/null
end

function __fold_templates
  fold ls --quiet --templates 2>/dev/null
end

function __fold_removal_targets
  __fold_cached_models
  __fold_profiles
end
EOF
}

# Generate Zsh completions for fold.
# Uses Zsh's _arguments state-machine approach with a nested case for profile
# subcommands. The heredoc uses a quoted delimiter ('ZSHEOF') so that bash
# does not expand the $, (), and other Zsh-specific syntax inside the body.
_completions_zsh() {
  local sn="$SCRIPT_NAME"
  cat <<'ZSHEOF'
#compdef fold
# Zsh completions for fold  (generated by: fold install)

_fold_cached_models() {
  local specs
  specs=(${(f)"$(fold ls --quiet --models 2>/dev/null | awk 'index($0, "/") > 0 { print $0 }')"})
  (( ${#specs[@]} )) && _values 'model[:quant]' "${specs[@]}"
}

_fold_profiles() {
  local names
  names=(${(f)"$(fold ls --quiet --profiles 2>/dev/null)"})
  (( ${#names[@]} )) && _values 'profile' "${names[@]}"
}

_fold_templates() {
  local names
  names=(${(f)"$(fold ls --quiet --templates 2>/dev/null)"})
  (( ${#names[@]} )) && _values 'template' "${names[@]}"
}

_fold_removal_targets() {
  _alternative 'models:model:_fold_cached_models' 'profiles:profile:_fold_profiles'
}

_fold() {
  local state
  _arguments \
    '1:command:->cmd' \
    '*::options:->opts'
  case $state in
    cmd)
      local cmds=(
        'install:Install llama.cpp'
        'update:Update llama.cpp to latest'
        'versions:List installed llama.cpp versions'
        'prune:Remove old llama.cpp versions'
        'uninstall:Uninstall llama.cpp'
        'status:Show installed version'
        'search:Search HuggingFace for compatible GGUF models'
        'browse:Open a model HuggingFace page in browser'
        'pull:Download a model without running'
        'list:List cached models' 'ls:List cached models'
        'remove:Remove a cached model' 'rm:Remove a cached model'
        'run:Run a model'
        'serve:Serve a model'
        'ps:Show running llama processes'
        'profile:Manage named run/serve profiles'
        'template:Manage templates'
        'help:Show help'
      )
      _describe 'command' cmds ;;
    opts)
      case $words[1] in
        install)
          _arguments \
            '--tag[Release tag]:tag' \
            '--path[Installation root]:dir:_files -/' \
            '--arch[Architecture]:arch:(macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64)' \
            '--shell-profile[Allow shell profile edits]' \
            '--no-shell-profile[Skip shell profile edits]' \
            '--print-latest-tag[Print latest tag and exit]' ;;
        update)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--arch[Architecture]:arch:(macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64)' \
            '--shell-profile[Allow shell profile edits]' \
            '--no-shell-profile[Skip shell profile edits]' ;;
        uninstall)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--delete-hf-cache[Delete cached HF model dirs]' \
            '--self[Also delete the fold script itself]' \
            '--force[Skip confirmation prompt]' ;;
        status)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--check-update[Check for newer release]' ;;
        search)
          _arguments \
            '--sort[Sort order]:by:(trending downloads likes newest)' \
            '--limit[Maximum number of results]:n' \
            '--quants[Show available quant variants]' \
            '--quiet[Only print model identifiers]' \
            '--json[JSON output]' ;;
        browse)
          _arguments '--print[Print URL instead of opening browser]' && _fold_cached_models ;;
        list|ls)
          _arguments '--quiet[Only print names]' '--json[JSON output]' '--models[Show models only]' '--profiles[Show profiles only]' '--templates[Show templates only]' ;;
        remove|rm)
          _arguments '--force[Skip confirmation prompt]' && _fold_removal_targets ;;
        pull)
          _fold_cached_models ;;
        run|serve)
          { _fold_cached_models; _fold_profiles } ;;
        profile)
          _arguments '1:subcommand:->sub' '*::profile-opts:->popts'
          case $state in
            sub)
              local subcmds=(
                'set:Create or replace a profile'
                'show:Print a profile'
                'duplicate:Copy a profile to a new name'
              )
              _describe 'profile subcommand' subcmds ;;
            popts)
              case $words[2] in
                show|duplicate) _fold_profiles ;;
              esac ;;
          esac ;;
        template)
          _arguments '1:subcommand:->sub' '*::template-opts:->topts'
          case $state in
            sub)
              local tsubcmds=(
                'show:Print a template'
                'set:Create or replace a user-defined template'
                'remove:Delete a user-defined template'
                'rm:Delete a user-defined template'
              )
              _describe 'template subcommand' tsubcmds ;;
            topts)
              case $words[2] in
                show|remove|rm) _fold_templates ;;
              esac ;;
          esac ;;
        versions)
          _arguments '--path[Installation root]:dir:_files -/' ;;
        prune)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--force[Skip confirmation prompt]' ;;
      esac ;;
  esac
}

_fold
ZSHEOF
}

# Generate Bash completions for fold.
# Registers a _fold_completions() function via 'complete -F'.
#
# COMP_WORDBREAKS: bash completion normally splits on ':', which would break
# "user/model:Q4_K_M" into two separate tokens. COMP_WORDBREAKS is narrowed
# (removing ':') for the duration of the completion call so that
# model:quant strings are treated as a single token for matching.
_completions_bash() {
  local sn="$SCRIPT_NAME"
  cat <<EOF
# Bash completions for $sn  (generated by: $sn install)
_${sn//-/_}_completions() {
  local cur prev words cword
  local _saved_wb="\$COMP_WORDBREAKS"
  COMP_WORDBREAKS="\${COMP_WORDBREAKS//:}"
  _init_completion 2>/dev/null || { cur="\${COMP_WORDS[COMP_CWORD]}"; prev="\${COMP_WORDS[COMP_CWORD-1]}"; }
  # shellcheck disable=SC2154
  local commands="install update versions prune uninstall status search browse pull list ls remove rm run serve ps profile template help"
  if [[ \$COMP_CWORD -eq 1 ]]; then
    COMPREPLY=(\$(compgen -W "\$commands" -- "\$cur"))
    COMP_WORDBREAKS="\$_saved_wb"
    return
  fi
  local cmd="\${COMP_WORDS[1]}"
  local -a models=() profiles=() templates=()
  while IFS= read -r _yl; do
    [[ -n "\$_yl" ]] && models+=("\$_yl")
  done < <(fold ls --quiet --models 2>/dev/null | awk 'index(\$0, "/") > 0 { print \$0 }')
  while IFS= read -r _yp; do
    [[ -n "\$_yp" ]] && profiles+=("\$_yp")
  done < <(fold ls --quiet --profiles 2>/dev/null)
  while IFS= read -r _yt; do
    [[ -n "\$_yt" ]] && templates+=("\$_yt")
  done < <(fold ls --quiet --templates 2>/dev/null)
  local -a removables=("${models[@]}" "${profiles[@]}")
  case "\$prev" in
    --path)  COMPREPLY=(\$(compgen -d -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --shell) COMPREPLY=(\$(compgen -W "fish zsh bash" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --arch)  COMPREPLY=(\$(compgen -W "macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --sort)  COMPREPLY=(\$(compgen -W "trending downloads likes newest" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
  esac
  case "\$cmd" in
    install)  COMPREPLY=(\$(compgen -W "--tag --path --arch --shell-profile --no-shell-profile --print-latest-tag" -- "\$cur")) ;;
    update)   COMPREPLY=(\$(compgen -W "--path --arch --shell-profile --no-shell-profile" -- "\$cur")) ;;
    uninstall) COMPREPLY=(\$(compgen -W "--path --delete-hf-cache --self --force" -- "\$cur")) ;;
    status)   COMPREPLY=(\$(compgen -W "--path --check-update" -- "\$cur")) ;;
    search)   COMPREPLY=(\$(compgen -W "--sort --limit --quants --quiet --json" -- "\$cur")) ;;
    browse)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--print" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\${models[*]}" -- "\$cur"))
      fi ;;
    list|ls)  COMPREPLY=(\$(compgen -W "--quiet --json --models --profiles --templates" -- "\$cur")) ;;
    pull)     COMPREPLY=(\$(compgen -W "\${models[*]}" -- "\$cur")) ;;
    run|serve)
      COMPREPLY=(\$(compgen -W "\${models[*]} \${profiles[*]}" -- "\$cur")) ;;
    remove|rm)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--force" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\${removables[*]}" -- "\$cur"))
      fi ;;
    profile)
      local profile_subcmds="set show duplicate"
      if [[ \$COMP_CWORD -eq 2 ]]; then
        COMPREPLY=(\$(compgen -W "\$profile_subcmds" -- "\$cur"))
      else
        local sub="\${COMP_WORDS[2]}"
        case "\$sub" in
          show|duplicate) COMPREPLY=(\$(compgen -W "\${profiles[*]}" -- "\$cur")) ;;
        esac
      fi ;;
    template)
      local template_subcmds="show set remove rm"
      if [[ \$COMP_CWORD -eq 2 ]]; then
        COMPREPLY=(\$(compgen -W "\$template_subcmds" -- "\$cur"))
      else
        local tsub="\${COMP_WORDS[2]}"
        case "\$tsub" in
          show|remove|rm) COMPREPLY=(\$(compgen -W "\${templates[*]}" -- "\$cur")) ;;
        esac
      fi ;;
    versions) COMPREPLY=(\$(compgen -W "--path" -- "\$cur")) ;;
    prune)    COMPREPLY=(\$(compgen -W "--path --force" -- "\$cur")) ;;
  esac
  COMP_WORDBREAKS="\$_saved_wb"
}
complete -F _${sn//-/_}_completions $sn
EOF
}
