# Shell completion generators for yallama.
# shellcheck shell=bash
# Each _completions_<shell>() function emits a heredoc of shell-native
# completion code; the output is written to the appropriate completions
# directory by install_completions() in yallama-runtime.sh.

# Generate Fish shell completions for yallama.
# Fish uses the __fish_seen_subcommand_from helper to scope completions
# to specific subcommands, with -n conditions as guards.
_completions_fish() {
  local sn="$SCRIPT_NAME"
  cat <<EOF
# Fish completions for $sn  (generated by: $sn install)

set -l commands install update versions prune uninstall status search browse pull list ls remove rm run serve ps profile help

# Disable file completion for all subcommands.
complete -c $sn -f

# Top-level commands.
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a install   -d 'Install llama.cpp'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a update    -d 'Update llama.cpp to latest'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a versions  -d 'List installed llama.cpp versions'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a prune     -d 'Remove old llama.cpp versions'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a uninstall -d 'Uninstall llama.cpp'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a status    -d 'Show installed version'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a search    -d 'Search HuggingFace for compatible GGUF models'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a browse    -d 'Open a model HuggingFace page in browser'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a pull      -d 'Download a model without running'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a list      -d 'List cached models'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a ls        -d 'List cached models (alias)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a remove    -d 'Remove a cached model'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a rm        -d 'Remove a cached model (alias)'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a run       -d 'Run a model'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a serve     -d 'Serve a model'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a ps        -d 'Show running llama processes'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a profile   -d 'Manage named run/serve profiles'
complete -c $sn -n "not __fish_seen_subcommand_from \$commands" -a help      -d 'Show help'

# Flags per subcommand.
complete -c $sn -n "__fish_seen_subcommand_from install"     -l tag              -d 'Release tag'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l arch           -d 'Architecture (e.g. macos-arm64)'
complete -c $sn -n "__fish_seen_subcommand_from install update versions prune uninstall status" -l path -d 'Installation root'
complete -c $sn -n "__fish_seen_subcommand_from install"     -l print-latest-tag -d 'Print latest tag and exit'
complete -c $sn -n "__fish_seen_subcommand_from status"      -l check-update     -d 'Check for newer release'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l shell-profile   -d 'Allow shell profile edits'
complete -c $sn -n "__fish_seen_subcommand_from install update" -l no-shell-profile -d 'Skip shell profile edits'
complete -c $sn -n "__fish_seen_subcommand_from uninstall"   -l delete-hf-cache  -d 'Delete cached HF model dirs'
complete -c $sn -n "__fish_seen_subcommand_from uninstall"   -l self             -d 'Also delete the yallama script itself'
complete -c $sn -n "__fish_seen_subcommand_from uninstall remove rm prune" -l force    -d 'Skip confirmation prompt'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l quiet            -d 'Only print names'
complete -c $sn -n "__fish_seen_subcommand_from list ls"     -l json             -d 'JSON output'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l sort             -d 'Sort order (trending, downloads, likes, newest)'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l limit            -d 'Maximum number of results'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l quants           -d 'Show available quant variants'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l quiet            -d 'Only print model identifiers'
complete -c $sn -n "__fish_seen_subcommand_from search"      -l json             -d 'JSON output'
complete -c $sn -n "__fish_seen_subcommand_from browse"      -l print            -d 'Print URL instead of opening browser'
complete -c $sn -n "__fish_seen_subcommand_from browse run serve pull remove rm" -a "(__yallama_cached_models)"
complete -c $sn -n "__fish_seen_subcommand_from run serve"   -a "(__yallama_profiles)"

# Profile subcommand completions.
set -l profile_subcmds set list show remove duplicate new templates template-show template-set template-remove
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a set             -d 'Create or replace a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a list            -d 'List all profiles'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a show            -d 'Print a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a remove          -d 'Delete a profile'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a duplicate       -d 'Copy a profile to a new name'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a new             -d 'Create a profile from a template'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a templates       -d 'List available templates'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a template-show   -d 'Print a template'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a template-set    -d 'Create or replace a user-defined template'
complete -c $sn -n "__fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from \$profile_subcmds" -a template-remove -d 'Delete a user-defined template'
complete -c $sn -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from show remove duplicate" -a "(__yallama_profiles)"
complete -c $sn -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from template-show template-remove" -a "(__yallama_templates)"
complete -c $sn -n "__fish_seen_subcommand_from profile; and __fish_seen_subcommand_from new" -a "(__yallama_templates) (__yallama_cached_models)"

# Model name completion for commands that take MODEL_NAME[:QUANT].
function __yallama_cached_models
  yallama ls --quiet 2>/dev/null
end

function __yallama_profiles
  yallama profile list 2>/dev/null | awk 'NR>2 && NF>=2 {print \$1}'
end

function __yallama_templates
  yallama profile templates 2>/dev/null | awk 'NR>2 {print \$1}'
end
EOF
}

# Generate Zsh completions for yallama.
# Uses Zsh's _arguments state-machine approach with a nested case for profile
# subcommands. The heredoc uses a quoted delimiter ('ZSHEOF') so that bash
# does not expand the $, (), and other Zsh-specific syntax inside the body.
_completions_zsh() {
  local sn="$SCRIPT_NAME"
  cat <<'ZSHEOF'
#compdef yallama
# Zsh completions for yallama  (generated by: yallama install)

_yallama_cached_models() {
  local specs
  specs=(${(f)"$(yallama ls --quiet 2>/dev/null)"})
  (( ${#specs[@]} )) && _values 'model[:quant]' "${specs[@]}"
}

_yallama_profiles() {
  local names
  names=(${(f)"$(yallama profile list 2>/dev/null | awk 'NR>2 && NF>=2 {print $1}')"})
  (( ${#names[@]} )) && _values 'profile' "${names[@]}"
}

_yallama_templates() {
  local names
  names=(${(f)"$(yallama profile templates 2>/dev/null | awk 'NR>2 {print $1}')"})
  (( ${#names[@]} )) && _values 'template' "${names[@]}"
}

_yallama() {
  local state
  _arguments \
    '1:command:->cmd' \
    '*::options:->opts'
  case $state in
    cmd)
      local cmds=(
        'install:Install llama.cpp'
        'update:Update llama.cpp to latest'
        'versions:List installed llama.cpp versions'
        'prune:Remove old llama.cpp versions'
        'uninstall:Uninstall llama.cpp'
        'status:Show installed version'
        'search:Search HuggingFace for compatible GGUF models'
        'browse:Open a model HuggingFace page in browser'
        'pull:Download a model without running'
        'list:List cached models' 'ls:List cached models'
        'remove:Remove a cached model' 'rm:Remove a cached model'
        'run:Run a model'
        'serve:Serve a model'
        'ps:Show running llama processes'
        'profile:Manage named run/serve profiles'
        'help:Show help'
      )
      _describe 'command' cmds ;;
    opts)
      case $words[1] in
        install)
          _arguments \
            '--tag[Release tag]:tag' \
            '--path[Installation root]:dir:_files -/' \
            '--arch[Architecture]:arch:(macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64)' \
            '--shell-profile[Allow shell profile edits]' \
            '--no-shell-profile[Skip shell profile edits]' \
            '--print-latest-tag[Print latest tag and exit]' ;;
        update)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--arch[Architecture]:arch:(macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64)' \
            '--shell-profile[Allow shell profile edits]' \
            '--no-shell-profile[Skip shell profile edits]' ;;
        uninstall)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--delete-hf-cache[Delete cached HF model dirs]' \
            '--self[Also delete the yallama script itself]' \
            '--force[Skip confirmation prompt]' ;;
        status)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--check-update[Check for newer release]' ;;
        search)
          _arguments \
            '--sort[Sort order]:by:(trending downloads likes newest)' \
            '--limit[Maximum number of results]:n' \
            '--quants[Show available quant variants]' \
            '--quiet[Only print model identifiers]' \
            '--json[JSON output]' ;;
        browse)
          _arguments '--print[Print URL instead of opening browser]' && _yallama_cached_models ;;
        list|ls)
          _arguments '--quiet[Only print names]' '--json[JSON output]' ;;
        remove|rm)
          _arguments '--force[Skip confirmation prompt]' && _yallama_cached_models ;;
        pull)
          _yallama_cached_models ;;
        run|serve)
          { _yallama_cached_models; _yallama_profiles } ;;
        profile)
          local profile_state
          _arguments '1:subcommand:->sub' '*::profile-opts:->popts'
          case $profile_state in
            sub)
              local subcmds=(
                'set:Create or replace a profile'
                'list:List all profiles'
                'show:Print a profile'
                'remove:Delete a profile'
                'duplicate:Copy a profile to a new name'
                'new:Create a profile from a template'
                'templates:List available templates'
                'template-show:Print a template'
                'template-set:Create or replace a user-defined template'
                'template-remove:Delete a user-defined template'
              )
              _describe 'profile subcommand' subcmds ;;
            popts)
              case $words[1] in
                show|remove|duplicate) _yallama_profiles ;;
                template-show|template-remove) _yallama_templates ;;
                new)
                  case $CURRENT in
                    3) _yallama_templates ;;
                    4) _yallama_cached_models ;;
                  esac ;;
              esac ;;
          esac ;;
        versions)
          _arguments '--path[Installation root]:dir:_files -/' ;;
        prune)
          _arguments \
            '--path[Installation root]:dir:_files -/' \
            '--force[Skip confirmation prompt]' ;;
      esac ;;
  esac
}

_yallama
ZSHEOF
}

# Generate Bash completions for yallama.
# Registers a _yallama_completions() function via 'complete -F'.
#
# COMP_WORDBREAKS: bash completion normally splits on ':', which would break
# "user/model:Q4_K_M" into two separate tokens. COMP_WORDBREAKS is narrowed
# (removing ':') for the duration of the completion call so that
# model:quant strings are treated as a single token for matching.
_completions_bash() {
  local sn="$SCRIPT_NAME"
  cat <<EOF
# Bash completions for $sn  (generated by: $sn install)
_${sn//-/_}_completions() {
  local cur prev words cword
  local _saved_wb="\$COMP_WORDBREAKS"
  COMP_WORDBREAKS="\${COMP_WORDBREAKS//:}"
  _init_completion 2>/dev/null || { cur="\${COMP_WORDS[COMP_CWORD]}"; prev="\${COMP_WORDS[COMP_CWORD-1]}"; }
  local commands="install update versions prune uninstall status search browse pull list ls remove rm run serve ps profile help"
  if [[ \$COMP_CWORD -eq 1 ]]; then
    COMPREPLY=(\$(compgen -W "\$commands" -- "\$cur"))
    COMP_WORDBREAKS="\$_saved_wb"
    return
  fi
  local cmd="\${COMP_WORDS[1]}"
  local models=()
  while IFS= read -r _yl; do
    [[ -n "\$_yl" ]] && models+=("\$_yl")
  done < <(yallama ls --quiet 2>/dev/null)
  local profiles=()
  while IFS= read -r _yp; do
    [[ -n "\$_yp" ]] && profiles+=("\$_yp")
  done < <(yallama profile list 2>/dev/null | awk 'NR>2 && NF>=2 {print \$1}')
  case "\$prev" in
    --path)  COMPREPLY=(\$(compgen -d -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --shell) COMPREPLY=(\$(compgen -W "fish zsh bash" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --arch)  COMPREPLY=(\$(compgen -W "macos-arm64 macos-x86_64 ubuntu-x64 ubuntu-arm64" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
    --sort)  COMPREPLY=(\$(compgen -W "trending downloads likes newest" -- "\$cur")); COMP_WORDBREAKS="\$_saved_wb"; return ;;
  esac
  case "\$cmd" in
    install)  COMPREPLY=(\$(compgen -W "--tag --path --arch --shell-profile --no-shell-profile --print-latest-tag" -- "\$cur")) ;;
    update)   COMPREPLY=(\$(compgen -W "--path --arch --shell-profile --no-shell-profile" -- "\$cur")) ;;
    uninstall) COMPREPLY=(\$(compgen -W "--path --delete-hf-cache --self --force" -- "\$cur")) ;;
    status)   COMPREPLY=(\$(compgen -W "--path --check-update" -- "\$cur")) ;;
    search)   COMPREPLY=(\$(compgen -W "--sort --limit --quants --quiet --json" -- "\$cur")) ;;
    browse)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--print" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\${models[*]}" -- "\$cur"))
      fi ;;
    list|ls)  COMPREPLY=(\$(compgen -W "--quiet --json" -- "\$cur")) ;;
    pull)     COMPREPLY=(\$(compgen -W "\${models[*]}" -- "\$cur")) ;;
    run|serve)
      COMPREPLY=(\$(compgen -W "\${models[*]} \${profiles[*]}" -- "\$cur")) ;;
    remove|rm)
      if [[ "\$cur" == --* ]]; then
        COMPREPLY=(\$(compgen -W "--force" -- "\$cur"))
      else
        COMPREPLY=(\$(compgen -W "\${models[*]}" -- "\$cur"))
      fi ;;
    profile)
      local profile_subcmds="set list show remove duplicate new templates template-show template-set template-remove"
      if [[ \$COMP_CWORD -eq 2 ]]; then
        COMPREPLY=(\$(compgen -W "\$profile_subcmds" -- "\$cur"))
      else
        local sub="\${COMP_WORDS[2]}"
        local templates=()
        while IFS= read -r _yt; do
          [[ -n "\$_yt" ]] && templates+=("\$_yt")
        done < <(yallama profile templates 2>/dev/null | awk 'NR>2 {print \$1}')
        case "\$sub" in
          show|remove|duplicate) COMPREPLY=(\$(compgen -W "\${profiles[*]}" -- "\$cur")) ;;
          template-show|template-remove) COMPREPLY=(\$(compgen -W "\${templates[*]}" -- "\$cur")) ;;
          new)
            case \$COMP_CWORD in
              4) COMPREPLY=(\$(compgen -W "\${templates[*]}" -- "\$cur")) ;;
              5) COMPREPLY=(\$(compgen -W "\${models[*]}" -- "\$cur")) ;;
            esac ;;
        esac
      fi ;;
    versions) COMPREPLY=(\$(compgen -W "--path" -- "\$cur")) ;;
    prune)    COMPREPLY=(\$(compgen -W "--path --force" -- "\$cur")) ;;
  esac
  COMP_WORDBREAKS="\$_saved_wb"
}
complete -F _${sn//-/_}_completions $sn
EOF
}
