#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_PATH="${ROOT_DIR}/src/corral.sh"
DEFAULT_OUTPUT_PATH="${ROOT_DIR}/dist/corral"

MODULES=(
  "src/lib/corral-helpers.sh"
  "src/lib/corral-cache.sh"
  "src/lib/corral-profiles.sh"
  "src/lib/corral-runtime.sh"
  "src/lib/corral-launch.sh"
  "src/lib/corral-search.sh"
  "src/lib/corral-completions.sh"
)

# Derive version from the nearest git tag; fall back to "dev" for untagged builds.
GIT_VERSION="$(git -C "$ROOT_DIR" describe --tags 2>/dev/null || echo "dev")"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--output <path> | --stdout]

Options:
  --output <path>  Write the generated standalone script to <path>. Default: dist/corral
  --stdout         Print the generated standalone script to stdout.
EOF
}

mode="write"
output_path="$DEFAULT_OUTPUT_PATH"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      output_path="${2:-}"
      [[ -n "$output_path" ]] || { echo "missing value for --output" >&2; exit 1; }
      shift 2
      ;;
    --stdout)
      mode="stdout"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

tmp_output="$(mktemp)"
cleanup() {
  rm -f "$tmp_output"
}
trap cleanup EXIT

# Process a module file, replacing BEGIN/END_BUILTIN_TEMPLATES and
# BEGIN/END_BUILTIN_TEMPLATE_NAMES blocks with inlined content derived
# from src/templates/*.conf files.  All other lines are passed through verbatim.
inline_module() {
  local module_path="$1"
  local _inside_block="false"
  local _mline
  while IFS= read -r _mline || [[ -n "$_mline" ]]; do
    local _marker_line="$_mline"
    _marker_line="${_marker_line#"${_marker_line%%[![:space:]]*}"}"
    case "$_marker_line" in
      '# BEGIN_BUILTIN_TEMPLATES')
        _inside_block="true"
        printf '%s\n' "$_mline"
        printf '  # This block is generated by tools/build.sh.\n'
        printf "  case \"\$name\" in\n"
        local _tf
        for _tf in "${ROOT_DIR}/src/templates"/*.conf; do
          [[ -f "$_tf" ]] || continue
          local _tn
          _tn="$(basename "$_tf" .conf)"
          printf '    %s)\n' "$_tn"
          printf "      cat <<'_CORRAL_BUILTIN_TPL_EOF'\n"
          cat "$_tf"
          printf '_CORRAL_BUILTIN_TPL_EOF\n'
          printf '      ;;\n'
        done
        printf '    *)\n'
        printf '      return 1\n'
        printf '      ;;\n'
        printf '  esac\n'
        ;;
      '# END_BUILTIN_TEMPLATES')
        _inside_block="false"
        printf '%s\n' "$_mline"
        ;;
      '# BEGIN_BUILTIN_TEMPLATE_NAMES')
        _inside_block="true"
        printf '%s\n' "$_mline"
        printf '  # This block is generated by tools/build.sh.\n'
        printf '  local -a builtin_names=('
        local _tnf
        for _tnf in "${ROOT_DIR}/src/templates"/*.conf; do
          [[ -f "$_tnf" ]] || continue
          local _tnn
          _tnn="$(basename "$_tnf" .conf)"
          printf ' %s' "$_tnn"
        done
        printf ' )\n'
        ;;
      '# END_BUILTIN_TEMPLATE_NAMES')
        _inside_block="false"
        printf '%s\n' "$_mline"
        ;;
      '# BEGIN_BUILTIN_LAUNCH_TEMPLATES')
        _inside_block="true"
        printf '%s\n' "$_mline"
        printf '  # This block is generated by tools/build.sh.\n'
        printf "  case \"\$name\" in\n"
        local _ltf
        for _ltf in "${ROOT_DIR}/src/launch-templates"/*.tmpl; do
          [[ -f "$_ltf" ]] || continue
          local _ltn
          _ltn="$(basename "$_ltf" .tmpl)"
          printf '    %s)\n' "$_ltn"
          printf "      cat <<'_CORRAL_BUILTIN_LAUNCH_TPL_EOF'\n"
          cat "$_ltf"
          printf '_CORRAL_BUILTIN_LAUNCH_TPL_EOF\n'
          printf '      ;;\n'
        done
        printf '    *)\n'
        printf '      return 1\n'
        printf '      ;;\n'
        printf '  esac\n'
        ;;
      '# END_BUILTIN_LAUNCH_TEMPLATES')
        _inside_block="false"
        printf '%s\n' "$_mline"
        ;;
      *)
        if [[ "$_inside_block" == "false" ]]; then
          printf '%s\n' "$_mline"
        fi
        ;;
    esac
  done < "$module_path"
}

found_begin="false"
found_end="false"
inside_generated_block="false"

while IFS= read -r line || [[ -n "$line" ]]; do
  case "$line" in
    '# BEGIN_GENERATED_MODULES')
      found_begin="true"
      inside_generated_block="true"
      {
        printf '%s\n' "$line"
        printf '# This block is generated by tools/build.sh.\n'
        for module in "${MODULES[@]}"; do
          printf '\n# --- %s ---\n' "$module"
          inline_module "${ROOT_DIR}/${module}"
          printf '\n'
        done
      } >> "$tmp_output"
      ;;
    '# END_GENERATED_MODULES')
      found_end="true"
      inside_generated_block="false"
      printf '%s\n' "$line" >> "$tmp_output"
      ;;
    *)
      if [[ "$inside_generated_block" == "false" ]]; then
        # Replace @VERSION@ placeholder with the current git tag.
        line="${line//@VERSION@/$GIT_VERSION}"
        printf '%s\n' "$line" >> "$tmp_output"
      fi
      ;;
  esac
done < "$TEMPLATE_PATH"

if [[ "$found_begin" != "true" || "$found_end" != "true" ]]; then
  echo "template is missing generated module markers: ${TEMPLATE_PATH}" >&2
  exit 1
fi

case "$mode" in
  stdout)
    cat "$tmp_output"
    ;;
  write)
    mkdir -p "$(dirname "$output_path")"
    cat "$tmp_output" > "$output_path"
    chmod +x "$output_path"
    echo "wrote standalone script: ${output_path}"
    ;;
esac
