#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_PATH="${ROOT_DIR}/src/fold.sh"
DEFAULT_OUTPUT_PATH="${ROOT_DIR}/dist/fold"

MODULES=(
  "src/lib/fold-helpers.sh"
  "src/lib/fold-cache.sh"
  "src/lib/fold-profiles.sh"
  "src/lib/fold-runtime.sh"
  "src/lib/fold-search.sh"
  "src/lib/fold-completions.sh"
)

# Derive version from the nearest git tag; fall back to "dev" for untagged builds.
GIT_VERSION="$(git -C "$ROOT_DIR" describe --tags 2>/dev/null || echo "dev")"

usage() {
  cat <<EOF
Usage: $(basename "$0") [--output <path> | --stdout]

Options:
  --output <path>  Write the generated standalone script to <path>. Default: dist/fold
  --stdout         Print the generated standalone script to stdout.
EOF
}

mode="write"
output_path="$DEFAULT_OUTPUT_PATH"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      output_path="${2:-}"
      [[ -n "$output_path" ]] || { echo "missing value for --output" >&2; exit 1; }
      shift 2
      ;;
    --stdout)
      mode="stdout"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

tmp_output="$(mktemp)"
cleanup() {
  rm -f "$tmp_output"
}
trap cleanup EXIT

found_begin="false"
found_end="false"
inside_generated_block="false"

while IFS= read -r line || [[ -n "$line" ]]; do
  case "$line" in
    '# BEGIN_GENERATED_MODULES')
      found_begin="true"
      inside_generated_block="true"
      {
        printf '%s\n' "$line"
        printf '# This block is generated by tools/build.sh.\n'
        for module in "${MODULES[@]}"; do
          printf '\n# --- %s ---\n' "$module"
          cat "${ROOT_DIR}/${module}"
          printf '\n'
        done
      } >> "$tmp_output"
      ;;
    '# END_GENERATED_MODULES')
      found_end="true"
      inside_generated_block="false"
      printf '%s\n' "$line" >> "$tmp_output"
      ;;
    *)
      if [[ "$inside_generated_block" == "false" ]]; then
        # Replace @VERSION@ placeholder with the current git tag.
        line="${line//@VERSION@/$GIT_VERSION}"
        printf '%s\n' "$line" >> "$tmp_output"
      fi
      ;;
  esac
done < "$TEMPLATE_PATH"

if [[ "$found_begin" != "true" || "$found_end" != "true" ]]; then
  echo "template is missing generated module markers: ${TEMPLATE_PATH}" >&2
  exit 1
fi

case "$mode" in
  stdout)
    cat "$tmp_output"
    ;;
  write)
    mkdir -p "$(dirname "$output_path")"
    cat "$tmp_output" > "$output_path"
    chmod +x "$output_path"
    echo "wrote standalone script: ${output_path}"
    ;;
esac
